name: Destroy ASG and Load Balancer

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Terragrunt
        run: |
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.1/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/
          terragrunt --version

      - name: Install Terraform
        run: |
          curl -L -o terraform.zip https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_amd64.zip
          unzip terraform.zip
          chmod +x terraform
          sudo mv terraform /usr/local/bin/
          terraform --version     

      - name: Destroy ASG and LB Resources
        run: |
          cd infrastructure/live/dev/asg
          terragrunt destroy -auto-approve